name: wedding-hall-backend
services:
- name: api
  build_command: npm install
  run_command: npm start
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "8080"
  http_port: 8080
  health_check:
    http_path: /health
  resources:
    memory_mb: 512
